create table if not exists public.community_signups (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 80),
  email text not null unique check (char_length(email) <= 254),
  interest text not null default 'Challenge videos',
  idea text check (idea is null or char_length(idea) <= 1000),
  consent boolean not null default false check (consent = true),
  created_at timestamptz not null default now()
);
alter table public.community_signups enable row level security;
drop policy if exists "Public can submit signups" on public.community_signups;
create policy "Public can submit signups" on public.community_signups
for insert to anon, authenticated
with check (consent = true and char_length(trim(name)) between 1 and 80
and char_length(trim(email)) between 3 and 254 and (idea is null or char_length(idea) <= 1000));
revoke all on table public.community_signups from anon, authenticated;
grant insert (name,email,interest,idea,consent) on public.community_signups to anon, authenticated;
grant usage, select on sequence public.community_signups_id_seq to anon, authenticated;
